name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v3.3.0
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'yoshiman'
        reponame: 'offline-qr-code-reader'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
